### ISSUE TITLE
EEG_distance_physionet.csv not found.

### ISSUE THREAD

**Issue by amar-enkhbat** [dalinzhang/GCRAM#1]
Hello, I'm trying to reproduce the results from the paper using this code. However, the EEG_distance_physionet.csv file for N-graph and S-graph are missing.

**Comment by dalinzhang** [comment]
Hi, the EEG_distance_physionet.csv only contains the positions of EEG nodes. This is not proposed by us so we do not include that in the repository. However, there are lots of sources for the information, such as related research articles, open-source EEG lib, or contact the EEG headset company.

**Comment by amar-enkhbat** [comment]
Thank you for your response. 
As mentioned above, I found the positions of EEG nodes on MNE-Python library, however the node distances are normalized. 
Will it result in same perforamce if I use normalized distance?

**Comment by amar-enkhbat** [comment]
Also, I have another question regarding cross-subject .mat file.
The paper mentions that the dataset:
"We prepared nine subject-independent evaluation sets (A01-A09), each of which contains ten randomly selected subjects as a test and the remaining 95 subjects as training". Does this mean that 10 subjects were randomly chosen and the rest were chosen for training for total of 11 evaluations?

**Comment by dalinzhang** [comment]
Hi, I did not try to normalize the distance. It might make a difference.
We randomly chose 10 subjects for training and the remaining 95 subjects for test. We randomly chose 9 times corresponding to 9 evaluations.
